### ISSUE TITLE
Failed to load png: No such file or directory

### ISSUE THREAD

**Issue by LoisNice** [visualboyadvance/visualboyadvance#3]
When I open the ROM,it shows this message.

**Comment by naegelejd** [comment]
It looks like vba is attempting load its icon PNG from `/usr/local/share/vba/icon/vba.png`. I just printed the filename in the culprit function:

``` diff
diff --git a/src/sdl/DisplaySDL.c b/src/sdl/DisplaySDL.c
index 4912fb5..892ae86 100644
--- a/src/sdl/DisplaySDL.c
+++ b/src/sdl/DisplaySDL.c
@@ -319,6 +319,7 @@ static png_bytep display_sdl_load_png_to_buffer(const gchar *filename, int *w, i
        memset(&image, 0, sizeof(image));
        image.version = PNG_IMAGE_VERSION;

+        fprintf(stderr, "%s\n", filename);
        if (!png_image_begin_read_from_file(&image, filename)) {
                g_set_error(err, DISPLAY_ERROR, G_DISPLAY_ERROR_FAILED,
                                "Failed to load png: %s", image.message);
```

There are 2 problems with this:
1. This won't work if you just run `vba` in the build directory and don't actually `make install`
2. This icon file is **not** installed at build time (see `CMakeLists.txt` line 136)

**Comment by bgK** [comment]
1. Actually vba first tries loading from the build directory, and then from the system location.
2. Right, fixed. Thanks.
