### ISSUE TITLE
Visualboy Advance not starting with RTC enabled

### ISSUE THREAD

**Issue by Eleuin** [visualboyadvance/visualboyadvance#4]
Starting a game normally shows that the real time clock is not enabled by default, which is needed for some games to function properly. To actually avoid the "internal battery has run dry" error, i have had to start VBA via command line using "vba --rtc <rom name>.gba".

**Comment by bgK** [comment]
I am pretty sure you are not reporting your bug against the correct version of VBA. This version does not have the "--rtc" option. It is also a command line only version, for now. And RTC is properly activated according the game database.
