### ISSUE TITLE
build failure in OSx 10.11

### ISSUE THREAD

**Issue by joybee007** [visualboyadvance/visualboyadvance#7]
Undefined symbols for architecture x86_64:
  "_archive_read_free", referenced from:
      _loader_load in libvbacore.a(Loader.c.o)
      _loader_open_archive in libvbacore.a(Loader.c.o)
      _loader_read_code in libvbacore.a(Loader.c.o)
  "_archive_read_support_filter_all", referenced from:
      _loader_open_archive in libvbacore.a(Loader.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bgK** [comment]
I don't have a Mac to try that, but it looks like libarchive is not recognized properly by the build system. Maybe you can look into it, and make sure it is properly set up on your system.

**Comment by aakashns** [comment]
I was facing the same problem. It was because `cmake` was using the system version of `libarchive`, which was 2.x, rather than the one installed through `brew`, which was 3.x. You can specify the location of `libarchive` as part of the `cmake` command :

```
cmake . -DLibArchive_LIBRARY=/usr/local/opt/libarchive/lib/libarchive.dylib -DLibArchive_INCLUDE_DIR=/usr/local/opt/libarchive/include
```

**Comment by joybee007** [comment]
Thanks I'll try.
